name: Q&A
on: push
jobs:
    tests:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run e2e tests (Cypress)
              uses: cypress-io/github-action@v5
              with:
                  component: true
                  build: npm run build
                  start: npm run start
                  wait-on: 'http://[::1]:3000'
            - name: Run unit tests (Jest)
              run: npm run test:unit:headless
    guidelines:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Format
              run: npm run format
            - name: Lint
              run: npm run lint

    types:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Types
              run: npm run types
